/**
 * lib/compositor/composition-fields.ts
 *
 * Shared field labels, placeholder copy, and the public entity-reference href builder for a
 * composition's detail view — consumed by both `CompositionInfo.astro` (the admin SSR card) and
 * `catalog.tsx`'s `CompositionDetail` Puck block (the public compositor render), so the two
 * independently-rendered views of the same ~25-field record cannot drift apart in wording (impl plan
 * Step 4). Only the *copy* lives here; each renderer keeps its own markup and per-field-kind logic
 * (Astro `set:html` anchors vs. React JSX) appropriate to its environment.
 *
 * `entityHref` targets the **public** `/entity/{noun}/{id}` route (the dangling convention already
 * consumed by `ListResult.astro`), distinct from `scripts/references.ts`'s admin-only
 * `/admin/{segment}/info?id=` helpers — the two link to different pages for different audiences and
 * must not be conflated.
 *
 * Not covered here: the composition notes' section headers ("Historical Notes" etc.) in
 * `CompositionInfo.astro` are generated by `admin-entities.css`'s `::before { content: … }` rather than
 * markup — a CSS string cannot import a TS constant, so that one instance stays a second copy by
 * necessity, not oversight. `COMPOSITION_LABELS.notesHistorical` etc. exist for `CompositionDetail`'s
 * own use and happen to match that CSS text; keep them in step by hand if either changes.
 *
 * Copyright (C) 2026 Michael Wong.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or any later version.
 *
 * This license is also subject to additional terms as specified in the README.md.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

import type { EntityNoun } from "./entity-fields"

/** Field labels shown beside a composition's values. Mirrors `CompositionInfo.astro`'s `<strong>` text. */
export const COMPOSITION_LABELS = {
    composer: "Composer",
    composerId: "Composer ID",
    secondaryAuthors: "Secondary Authors",
    secondaryAuthorIds: "Secondary Author IDs",
    primaryContributor: "Primary Contributor ID",
    additionalPrimaryContributor: "Additional Primary Contributor ID",
    additionalContributors: "Additional Contributor IDs",
    phases: "Phases",
    key: "Key",
    range: "Range",
    highestPosition: "Highest Position",
    suzukiRating: "Suzuki Rating",
    nyssmaRating: "NYSSMA Rating",
    publisherName: "Publisher Name",
    publicationLocation: "Publication Location",
    publicationYear: "Publication Year",
    publicationUri: "Publication URI",
    notesHistorical: "Historical Notes",
    notesPedagogical: "Pedagogical Notes",
    notesOther: "Other Notes",
    tags: "Tags"
} as const

/** "Not supplied" copy for each field. Mirrors `CompositionInfo.astro`'s `disp()`/anchor placeholder args. */
export const COMPOSITION_PLACEHOLDERS = {
    type: "(no type specified)",
    part: "(no part specified)",
    composerNameError: "(error in composer name)",
    secondaryAuthors: "(no secondary authors)",
    secondaryAuthorIds: "(no secondary author IDs)",
    additionalPrimaryContributor: "(no additional primary contributor specified)",
    additionalContributors: "(no additional contributors specified)",
    phases: "(no phases specified)",
    key: "(no key specified)",
    range: "(no range specified)",
    highestPosition: "(no position specified)",
    publisherName: "(no publisher name specified)",
    publicationLocation: "(no publication location specified)",
    publicationYear: "(no publication year specified)",
    publicationUri: "(no publication URI specified)",
    notesHistorical: "(no historical notes)",
    notesPedagogical: "(no pedagogical notes)",
    notesOther: "(no other notes)"
} as const

/**
 * Renders a field value for display, substituting the placeholder when the value is null, undefined,
 * blank, or an empty array — so "not supplied" reads as visually distinct from an unset/blank render.
 * Shared by `CompositionInfo.astro` (as its local `disp`) and `CompositionDetail` (catalog.tsx), so a
 * formatting change (e.g. how arrays join) can't drift between the two independently-rendered views.
 *
 * @param {unknown} value - the raw field value
 * @param {string} placeholder - the text to show when the value carries nothing
 * @returns {string} the display string
 */
export function displayValue(value: unknown, placeholder: string): string {
    if (value === null || value === undefined) return placeholder
    if (Array.isArray(value)) return value.length > 0 ? value.join(", ") : placeholder
    if (typeof value === "string" && value.trim() === "") return placeholder
    if (typeof value === "boolean") return value ? "Yes" : "No"
    return String(value)
}

/**
 * The public detail-page URL for an entity reference (a composer or contributor a composition names).
 * Matches the `/entity/{noun}/{id}` convention `ListResult.astro` already links to; Step 6 is what makes
 * these resolve to an actual page.
 *
 * @param {EntityNoun} noun - "composer" or "contributor" (the two reference types a composition holds)
 * @param {number} id - the referenced record's id
 * @returns {string} the public entity URL
 */
export function entityHref(noun: EntityNoun, id: number): string {
    return `/entity/${noun}/${id}`
}
