/**
 * Stub Worker entrypoint for vitest-pool-workers
 *
 * The deployed Worker's main entry (@astrojs/cloudflare/entrypoints/server in wrangler.jsonc)
 * is generated by the Astro build and cannot be resolved by the test pool. Tests import library
 * modules directly and only need the bindings/env from wrangler.jsonc, so this stub satisfies
 * the pool's requirement for a resolvable main module.
 *
 * Copyright (C) 2026 Michael Wong.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or any later version.
 *
 * This license is also subject to additional terms as specified in the README.md.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

export default {
    async fetch(): Promise<Response> {
        return new Response("test worker stub")
    }
}
