/**
 * Stub Worker entrypoint for vitest-pool-workers
 *
 * The deployed Worker's main entry (@astrojs/cloudflare/entrypoints/server in wrangler.jsonc)
 * is generated by the Astro build and cannot be resolved by the test pool. Tests import library
 * modules directly and only need the bindings/env from wrangler.jsonc, so this stub satisfies
 * the pool's requirement for a resolvable main module.
 */

export default {
    async fetch(): Promise<Response> {
        return new Response("test worker stub")
    }
}
