/**
 * pages/sitemap.xml.ts
 *
 * Alias for the conventional /sitemap.xml path. @astrojs/sitemap (astro.config.mjs) only ever emits
 * /sitemap-index.xml (+ /sitemap-0.xml, ...) — it has no option to name its output sitemap.xml — but
 * that's the path most crawlers, webmaster tools, and humans check first.
 *
 * Prerendered, so it can't issue an HTTP redirect (a static file has no status code) or read
 * sitemap-index.xml's generated bytes (the sitemap integration writes that in its own astro:build:done
 * hook, after this page has already rendered). Instead this page IS a valid sitemapindex document that
 * points straight at sitemap-0.xml, the actual urlset — a sitemapindex nesting another sitemapindex isn't
 * spec-valid, so this can't just point at sitemap-index.xml.
 *
 * Assumption: the site stays under @astrojs/sitemap's 45,000-URL-per-file default (entryLimit), so it
 * only ever emits sitemap-0.xml. If the build ever splits into sitemap-1.xml etc., this needs to either
 * list every chunk or go back to a runtime redirect to sitemap-index.xml.
 *
 * Copyright (C) 2026 Michael Wong.
 *
 * This file is part of the spot-kilmerviolin-website program, available at
 * https://github.com/micawoken/spot-kilmerviolin-website.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This license is also subject to additional terms as specified in the README.md.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
import type { APIRoute } from "astro"

export const prerender = true

export const GET: APIRoute = ({ site }) => {
    const sitemapUrl = new URL("/sitemap-0.xml", site)
    const body = `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>${sitemapUrl.href}</loc></sitemap></sitemapindex>\n`

    return new Response(body, { headers: { "Content-Type": "application/xml" } })
}
